package fetch

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"

	bothy "github.com/bspeelm/bothy"
	"github.com/bspeelm/bothy/internal/platform"
	"github.com/bspeelm/bothy/internal/probe"
	"github.com/bspeelm/bothy/internal/tools"
)

// Lockfile pins the exact version and checksum of every tool bothy may
// install, so two machines running the same bothy get the same binaries and a
// tampered release fails hard rather than substituting silently. It is
// regenerated by `bothy lock`, never automatically during an install: pins
// that move by themselves reproduce nothing.
type Lockfile struct {
	Entries []Entry `toml:"tool"`
}

// Entry is one pinned tool.
type Entry struct {
	Name string `toml:"name"`
	// Tag is the upstream release tag, verbatim ("v0.45.1", "0.19.2",
	// "jq-1.8.2"). Version is that tag with the decoration removed, which is
	// what asset names interpolate.
	Tag     string `toml:"tag"`
	Version string `toml:"version"`
	// SHA256 is keyed by "<os>_<arch>".
	SHA256 map[string]string `toml:"sha256"`
	// Verified lists the platforms whose checksum was confirmed against one
	// the project published itself, rather than only computed from the bytes
	// GitHub served.
	Verified []string `toml:"verified,omitempty"`
}

// SHA returns the checksum for a platform, or "" if this entry has none.
func (e Entry) SHA(p platform.Info) string { return e.SHA256[p.OS+"_"+p.Arch] }

// CrossChecked reports whether this platform's pin was compared with a
// checksum the project published, rather than only computed from the download.
func (e Entry) CrossChecked(p platform.Info) bool {
	return slices.Contains(e.Verified, p.OS+"_"+p.Arch)
}

// APIBase is GitHub's API root, as a variable so a test can point it at a
// local server rather than the internet.
var APIBase = "https://api.github.com"

// LockPath is the lockfile's name at the repository root.
const LockPath = "bothy.lock"

// LoadLock reads the lockfile compiled into the binary. It is embedded rather
// than read from disk because an installed bothy has no repository to read
// from, and the pins are part of what a given bothy release *is*.
func LoadLock() (*Lockfile, error) {
	return ParseLock(bothy.Lock())
}

// ParseLock reads a lockfile from bytes.
func ParseLock(src []byte) (*Lockfile, error) {
	var l Lockfile
	if err := toml.Unmarshal(src, &l); err != nil {
		return nil, fmt.Errorf("fetch: %s: %w", LockPath, err)
	}
	return &l, nil
}

// LoadLockFile reads a lockfile from disk, for `bothy lock` to update.
func LoadLockFile(path string) (*Lockfile, error) {
	src, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return &Lockfile{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("fetch: %w", err)
	}
	return ParseLock(src)
}

// Get returns the entry for a tool.
func (l *Lockfile) Get(name string) (Entry, bool) {
	for _, e := range l.Entries {
		if e.Name == name {
			return e, true
		}
	}
	return Entry{}, false
}

// Set adds or replaces an entry.
func (l *Lockfile) Set(e Entry) {
	for i := range l.Entries {
		if l.Entries[i].Name == e.Name {
			l.Entries[i] = e
			return
		}
	}
	l.Entries = append(l.Entries, e)
}

// Save writes the lockfile, sorted so a regeneration produces a reviewable diff
// rather than a reshuffle.
func (l *Lockfile) Save(path string) error {
	sort.Slice(l.Entries, func(i, j int) bool { return l.Entries[i].Name < l.Entries[j].Name })
	out, err := toml.Marshal(l)
	if err != nil {
		return fmt.Errorf("fetch: %w", err)
	}
	header := "# Pinned tool versions and checksums.\n" +
		"# Regenerate with 'bothy lock'; review the diff before committing.\n" +
		"# An install fetches exactly these and verifies the checksum first.\n\n"
	return os.WriteFile(path, append([]byte(header), out...), 0o644)
}

// upstreamSum reads the sha256 a project published for one asset, or "" when
// it published none. The file is "<sha256>  <filename>" lines either way, so
// both shapes are read by matching the filename -- or, where
// checksum_covers = "binary", its basename: zellij names the line by the
// binary's build path, which matches no asset.
func upstreamSum(t tools.Tool, p platform.Info, tag, version, asset string) (string, error) {
	name, err := t.ChecksumFile(p, version)
	if err != nil || name == "" {
		return "", err
	}
	body, err := Download(ReleaseURL(t.Repo, tag, name))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(body), "\n") {
		f := strings.Fields(line)
		if len(f) != 2 {
			continue
		}
		listed := strings.TrimPrefix(f[1], "*")
		if listed == asset || (t.ChecksumCovers == "binary" && path.Base(listed) == t.Binary) {
			return strings.ToLower(f[0]), nil
		}
	}
	return "", fmt.Errorf("%s does not list %s", name, asset)
}

// gitDescribe matches the "-g<sha>" a `git describe` version carries.
var gitDescribe = regexp.MustCompile(`-g[0-9a-f]{7,}`)

// IsSourceBuild reports whether a version came from `git describe` rather than
// a release tag -- whether it is *ahead* of the tag it names. The shape is
// "v0.1.5-3-gabc1234-dirty"; only a bare `go build` yields "dev". Update
// .Outdated compares by string inequality, which would otherwise announce an
// upgrade to someone already past it.
func IsSourceBuild(v string) bool {
	return v == "" || v == "dev" ||
		strings.HasSuffix(v, "-dirty") ||
		gitDescribe.MatchString(v)
}

// LatestRelease asks GitHub for a repository's latest release tag.
func LatestRelease(repo string) (string, error) {
	req, err := http.NewRequest(http.MethodGet, APIBase+"/repos/"+repo+"/releases/latest", nil)
	if err != nil {
		return "", fmt.Errorf("fetch: %s: %w", repo, err)
	}
	req.Header.Set("User-Agent", "bothy")
	req.Header.Set("Accept", "application/vnd.github+json")
	// Unauthenticated requests are capped at sixty an hour per IP, which a
	// shared CI runner burns on someone else's behalf; a token lifts it to five
	// thousand and is not required.
	if tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := Client.Do(req)
	if err != nil {
		return "", fmt.Errorf("fetch: %s: %w", repo, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("fetch: %s: HTTP %d from the releases API", repo, resp.StatusCode)
	}
	var payload struct {
		TagName string `json:"tag_name"`
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return "", fmt.Errorf("fetch: %s: %w", repo, err)
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return "", fmt.Errorf("fetch: %s: %w", repo, err)
	}
	if payload.TagName == "" {
		return "", fmt.Errorf("fetch: %s: no tag in the latest release", repo)
	}
	return payload.TagName, nil
}

// VersionFromTag strips the decoration a project puts on its tags.
//
//	v0.45.1   -> 0.45.1     (most)
//	0.19.2    -> 0.19.2     (ripgrep)
//	jq-1.8.2  -> 1.8.2      (jq)
func VersionFromTag(tag string) string {
	// Strip a leading "<name>-" prefix, and only that: the version starts at
	// the first digit after it. Keying on a later hyphen would eat suffixes --
	// "v1.2.3-rc.1" would become "rc.1" -- and a garbage version silently
	// breaks every asset-name interpolation that follows.
	if i := strings.IndexByte(tag, '-'); i >= 0 && i+1 < len(tag) {
		if rest := tag[i+1:]; rest[0] >= '0' && rest[0] <= '9' && !isDigits(tag[:i]) {
			tag = rest
		}
	}
	return strings.TrimPrefix(tag, "v")
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

// Platforms are the targets a lockfile records checksums for.
var Platforms = []platform.Info{
	{OS: "linux", Arch: "x86_64"},
	{OS: "linux", Arch: "aarch64"},
	{OS: "darwin", Arch: "x86_64"},
	{OS: "darwin", Arch: "aarch64"},
}

// Relock refreshes one tool's entry at the latest release.
func Relock(t tools.Tool, progress func(string)) (Entry, error) {
	tag, err := LatestRelease(t.Repo)
	if err != nil {
		return Entry{}, err
	}
	return RelockAt(t, tag, progress)
}

// RelockAt refreshes one tool's entry at a given tag: download every
// platform's asset and record its checksum. Downloading real assets is slow
// and deliberate -- a checksum copied from a metadata endpoint rather than
// computed from the bytes bothy will run verifies nothing.
func RelockAt(t tools.Tool, tag string, progress func(string)) (Entry, error) {
	version := VersionFromTag(tag)

	e := Entry{Name: t.Name, Tag: tag, Version: version, SHA256: map[string]string{}}
	for _, p := range Platforms {
		asset, err := t.Asset(p, version)
		if err != nil {
			continue // this tool does not target that platform
		}
		url := ReleaseURL(t.Repo, tag, asset)
		if progress != nil {
			progress(fmt.Sprintf("  %s %s %s_%s", t.Name, version, p.OS, p.Arch))
		}
		body, err := Download(url)
		if err != nil {
			// A platform the project does not publish for is an absent
			// checksum, not an error; Install refuses to proceed without one.
			if progress != nil {
				progress(fmt.Sprintf("    skipped: %v", err))
			}
			continue
		}
		sum := Sum(body)
		e.SHA256[p.OS+"_"+p.Arch] = sum

		// The pin is always the asset's hash: that is what Install checks
		// before unpacking. The cross-check may be against the binary inside.
		mine := sum
		if t.ChecksumCovers == "binary" {
			found, err := Extract(body, asset, []string{t.Binary})
			if err != nil || found[t.Binary] == nil {
				return Entry{}, fmt.Errorf(
					"fetch: %s %s %s_%s: cannot read %s out of %s to compare with the "+
						"published checksum: %v", t.Name, version, p.OS, p.Arch, t.Binary, asset, err)
			}
			mine = Sum(found[t.Binary])
		}

		// Cross-check against what the project published, where it publishes
		// anything. A hash of the bytes GitHub served is trust-on-first-use;
		// a match with the release's own file rules out substitution after
		// publication, and nothing before it.
		switch upstream, err := upstreamSum(t, p, tag, version, asset); {
		case err != nil:
			if progress != nil {
				progress("    upstream checksum unreadable: " + err.Error())
			}
		case upstream == "":
			if progress != nil {
				progress("    no upstream checksum published")
			}
		case upstream != mine:
			// Hard failure: this is the case reading the upstream value exists
			// to catch.
			return Entry{}, fmt.Errorf(
				"fetch: %s %s %s_%s: upstream checksum does not match what was downloaded\n"+
					"      upstream %s\n      download %s",
				t.Name, version, p.OS, p.Arch, upstream, mine)
		default:
			e.Verified = append(e.Verified, p.OS+"_"+p.Arch)
			if progress != nil {
				progress("    upstream checksum matched")
			}
		}
	}
	if len(e.SHA256) == 0 {
		return Entry{}, fmt.Errorf("fetch: %s %s: no asset downloaded for any platform", t.Name, tag)
	}
	return e, nil
}

// parseLockVersion is probe.ParseVersion, re-exported for tests that check a
// pinned version against the tool's own minimum.
func parseLockVersion(v string) (probe.Version, error) { return probe.ParseVersion(v) }
