// Package render writes generated config files into the places the tools
// insist on reading them from, without ever destroying what was already there.
//
// The contract, from PLAN.md §1:
//
//   - Every generated file starts with a header identifying it as bothy's.
//   - A file that exists without that header belongs to the user: it is copied
//     to the backup directory and recorded in the manifest before being replaced.
//   - A file that exists *with* the header is bothy's own previous output and is
//     simply overwritten — but only if it still hashes to what bothy wrote. A
//     hand-edited managed file is left alone and reported, because silently
//     discarding someone's edit is the one unrecoverable mistake here.
package render

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/bothy-dev/bothy/internal/state"
)

// Marker is the string that identifies a bothy-managed file. It appears inside
// a comment whose syntax varies by file type, so detection looks for the marker
// anywhere in the first few lines rather than for an exact prefix.
const Marker = "managed by bothy"

// HeaderLines is how far into a file the marker may appear. Generous enough for
// a shebang or a mode line above it, tight enough that the marker appearing in
// a user's own prose deep in a file cannot be mistaken for the header.
const HeaderLines = 5

// Comment styles for the file types bothy generates.
var commentPrefix = map[string]string{
	".toml": "#", ".kdl": "//", ".lua": "--", ".vim": "\"",
	".sh": "#", ".bash": "#", ".conf": "#", ".ini": "#", ".yaml": "#", ".yml": "#",
}

// Header returns the managed-file banner for a destination path, in that file
// type's comment syntax.
func Header(dest string) string {
	c := commentPrefix[filepath.Ext(dest)]
	if c == "" {
		c = "#"
	}
	return fmt.Sprintf(
		"%s %s — do not edit this file directly.\n"+
			"%s Put your changes in %s and run 'bothy install' to regenerate.\n",
		c, Marker, c, overrideHint(dest))
}

func overrideHint(dest string) string {
	return filepath.Join("~/.config/bothy/overrides", toolOf(dest), filepath.Base(dest))
}

// toolOf guesses which tool a destination belongs to, for the override path.
// It is the parent directory name for XDG configs (~/.config/yazi/yazi.toml ->
// "yazi") and the stem for dotfiles in home (~/.vimrc -> "vim").
func toolOf(dest string) string {
	dir := filepath.Base(filepath.Dir(dest))
	if dir != "" && dir != "." && dir != string(filepath.Separator) && !strings.HasPrefix(dir, ".") {
		return dir
	}
	base := strings.TrimPrefix(filepath.Base(dest), ".")
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// IsManaged reports whether a file carries bothy's header.
func IsManaged(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, 4096)
	n, _ := f.Read(buf)
	head := string(buf[:n])
	if i := nthLineEnd(head, HeaderLines); i >= 0 {
		head = head[:i]
	}
	return strings.Contains(head, Marker)
}

func nthLineEnd(s string, n int) int {
	idx := 0
	for i := 0; i < n; i++ {
		j := strings.IndexByte(s[idx:], '\n')
		if j < 0 {
			return -1
		}
		idx += j + 1
	}
	return idx
}

// Writer renders templates and writes them, recording everything it does.
type Writer struct {
	Manifest  *state.Manifest
	StateHome string
	Home      string
	// Overrides is ~/.config/bothy/overrides; content found there is appended
	// after the rendered template.
	Overrides string
	// DryRun reports what would happen without touching the filesystem.
	DryRun bool

	backupDir string
	started   time.Time
	// Skipped collects managed files that were edited by hand and therefore
	// left alone, so the caller can tell the user rather than silently ignoring.
	Skipped []string
}

// NewWriter constructs a Writer for one install run.
func NewWriter(m *state.Manifest, stateHome, home, overrides string) *Writer {
	now := time.Now()
	return &Writer{
		Manifest:  m,
		StateHome: stateHome,
		Home:      home,
		Overrides: overrides,
		started:   now,
		backupDir: state.BackupDir(stateHome, now),
	}
}

// Render executes a template with the given data and returns the bytes that
// would be written, header and overrides included.
func (w *Writer) Render(dest, tmplName, tmplText string, data any) ([]byte, error) {
	t, err := template.New(tmplName).Funcs(funcs()).Parse(tmplText)
	if err != nil {
		return nil, fmt.Errorf("render: parsing %s: %w", tmplName, err)
	}
	var body bytes.Buffer
	body.WriteString(Header(dest))
	if err := t.Execute(&body, data); err != nil {
		return nil, fmt.Errorf("render: executing %s: %w", tmplName, err)
	}

	extra, err := w.override(dest)
	if err != nil {
		return nil, err
	}
	if len(extra) > 0 {
		c := commentPrefix[filepath.Ext(dest)]
		if c == "" {
			c = "#"
		}
		fmt.Fprintf(&body, "\n%s --- from %s ---\n", c, overrideHint(dest))
		body.Write(extra)
		if !bytes.HasSuffix(extra, []byte("\n")) {
			body.WriteByte('\n')
		}
	}
	return body.Bytes(), nil
}

// override reads the user's addition for a destination, if any.
//
// The merge rule is deliberately dumb — append, and nothing else. Every format
// bothy writes (TOML, KDL, Lua, vimscript) is one where a later statement wins
// or adds, and a real structural merge would need a parser per format plus a
// story for conflicts. "Append and document it" is the version that keeps
// working when a tool adds a new config key.
func (w *Writer) override(dest string) ([]byte, error) {
	if w.Overrides == "" {
		return nil, nil
	}
	path := filepath.Join(w.Overrides, toolOf(dest), filepath.Base(dest))
	b, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("render: reading override %s: %w", path, err)
	}
	return b, nil
}

// Write puts content at dest, backing up whatever was there.
//
// It returns whether the file changed, so an install can report "3 files
// written, 9 already current" instead of claiming to have rewritten the world.
func (w *Writer) Write(dest string, content []byte) (changed bool, err error) {
	existing, err := os.ReadFile(dest)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		// Nothing there; nothing to preserve.
	case err != nil:
		return false, fmt.Errorf("render: %s: %w", dest, err)
	default:
		if bytes.Equal(existing, content) {
			// Still record it: a file bothy did not have to rewrite is still a
			// file bothy owns and must remove on uninstall.
			w.Manifest.RecordFile(state.File{Path: dest, SHA256: state.HashBytes(content)})
			return false, nil
		}
		if IsManaged(dest) {
			// bothy's own output. Overwrite it — unless it drifted from what
			// bothy last wrote, which means someone edited it by hand.
			if rec, ok := w.Manifest.FileFor(dest); ok && rec.SHA256 != "" &&
				rec.SHA256 != state.HashBytes(existing) {
				w.Skipped = append(w.Skipped, dest)
				return false, nil
			}
		} else if err := w.backup(dest, existing); err != nil {
			return false, err
		}
	}

	if w.DryRun {
		return true, nil
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return false, fmt.Errorf("render: %s: %w", dest, err)
	}
	if err := writeAtomic(dest, content, 0o644); err != nil {
		return false, fmt.Errorf("render: %s: %w", dest, err)
	}
	w.Manifest.RecordFile(state.File{Path: dest, SHA256: state.HashBytes(content)})
	return true, nil
}

// backup copies a user's pre-existing file aside and records where it went.
func (w *Writer) backup(dest string, content []byte) error {
	rel := strings.TrimPrefix(dest, w.Home)
	rel = strings.TrimPrefix(rel, string(filepath.Separator))
	dst := filepath.Join(w.backupDir, rel)

	if !w.DryRun {
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return fmt.Errorf("render: backing up %s: %w", dest, err)
		}
		if err := os.WriteFile(dst, content, 0o644); err != nil {
			return fmt.Errorf("render: backing up %s: %w", dest, err)
		}
	}
	w.Manifest.RecordFile(state.File{Path: dest, Backup: dst})
	return nil
}

// WriteExec writes an executable file (the xdg-open shim, mainly).
func (w *Writer) WriteExec(dest string, content []byte) (bool, error) {
	changed, err := w.Write(dest, content)
	if err != nil || w.DryRun {
		return changed, err
	}
	return changed, os.Chmod(dest, 0o755)
}

// BackupDir is where this run's backups went, for reporting.
func (w *Writer) BackupDir() string { return w.backupDir }

// writeAtomic writes via a temporary file and renames, so an interrupted write
// cannot leave a tool reading a truncated config.
func writeAtomic(dest string, content []byte, mode fs.FileMode) error {
	tmp := dest + ".bothy-tmp"
	if err := os.WriteFile(tmp, content, mode); err != nil {
		return err
	}
	if err := os.Rename(tmp, dest); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}

// funcs is the template function set. It stays small on purpose: a template
// that needs more logic than this is a sign the providers should be split
// instead (PLAN.md §1, "no conditionals sprawl").
func funcs() template.FuncMap {
	return template.FuncMap{
		"join":  strings.Join,
		"quote": func(s string) string { return fmt.Sprintf("%q", s) },
		"default": func(def, v string) string {
			if v == "" {
				return def
			}
			return v
		},
	}
}
