// Package render turns templates into the config files bothy launches its
// tools against.
//
// Everything it writes goes inside bothy's own tree (ADR-009), which is what
// lets this package be as small as it is. Revision 1 needed backups, content
// hashes and drift detection because it wrote into files the user owned;
// isolation removes the problem rather than managing it.
//
// Two things survive from that design and earn their place:
//
//   - Every generated file says it is generated, and names where to put your
//     own changes. A file with no provenance is a file nobody dares edit.
//   - Overrides are appended after the template, so your setting wins.
package render

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Marker identifies a bothy-generated file. It appears inside a comment whose
// syntax varies by file type, so detection looks for the marker in the first
// few lines rather than for an exact prefix.
const Marker = "generated by bothy"

// HeaderLines is how far into a file the marker may appear.
const HeaderLines = 5

// Comment styles for the file types bothy generates.
var commentPrefix = map[string]string{
	".toml": "#", ".kdl": "//", ".lua": "--", ".vim": "\"",
	".sh": "#", ".bash": "#", ".conf": "#", ".ini": "#", ".yaml": "#", ".yml": "#",
}

// Header returns the banner for a destination path, in that file type's
// comment syntax.
func Header(dest, tool string) string {
	c := commentPrefix[filepath.Ext(dest)]
	if c == "" {
		c = "#"
	}
	return fmt.Sprintf(
		"%s %s. Regenerated by 'bothy install'; edits here are lost.\n"+
			"%s Put your own changes in ~/.config/bothy/overrides/%s/%s — they are\n"+
			"%s appended after this file, so they win.\n",
		c, Marker, c, tool, filepath.Base(dest), c)
}

// IsGenerated reports whether a file carries bothy's header.
func IsGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, 4096)
	n, _ := f.Read(buf)
	head := string(buf[:n])
	if i := nthLineEnd(head, HeaderLines); i >= 0 {
		head = head[:i]
	}
	return strings.Contains(head, Marker)
}

func nthLineEnd(s string, n int) int {
	idx := 0
	for i := 0; i < n; i++ {
		j := strings.IndexByte(s[idx:], '\n')
		if j < 0 {
			return -1
		}
		idx += j + 1
	}
	return idx
}

// Writer renders templates into bothy's tree.
type Writer struct {
	// Root is bothy's tree — config/ and bin/ both live under it. Every write
	// must land inside it; the Write method refuses anything else, which is
	// the isolation promise enforced rather than merely intended.
	Root string
	// Overrides is ~/.config/bothy/overrides.
	Overrides string
	// DryRun reports what would happen without touching the filesystem.
	DryRun bool
}

// NewWriter constructs a Writer for one install run.
func NewWriter(root, overrides string) *Writer {
	return &Writer{Root: root, Overrides: overrides}
}

// Render executes a template and returns the bytes to write, header and
// overrides included. tool names the override subdirectory.
func (w *Writer) Render(dest, tool, tmplName, tmplText string, data any) ([]byte, error) {
	t, err := template.New(tmplName).Funcs(funcs()).Parse(tmplText)
	if err != nil {
		return nil, fmt.Errorf("render: parsing %s: %w", tmplName, err)
	}
	var body bytes.Buffer
	body.WriteString(Header(dest, tool))
	if err := t.Execute(&body, data); err != nil {
		return nil, fmt.Errorf("render: executing %s: %w", tmplName, err)
	}

	extra, err := w.override(tool, filepath.Base(dest))
	if err != nil {
		return nil, err
	}
	if len(extra) > 0 {
		c := commentPrefix[filepath.Ext(dest)]
		if c == "" {
			c = "#"
		}
		fmt.Fprintf(&body, "\n%s --- from ~/.config/bothy/overrides/%s/%s ---\n",
			c, tool, filepath.Base(dest))
		body.Write(extra)
		if !bytes.HasSuffix(extra, []byte("\n")) {
			body.WriteByte('\n')
		}
	}
	return body.Bytes(), nil
}

// override reads the user's addition for a file, if any.
//
// The merge rule is deliberately dumb — append, and nothing else. Every format
// bothy writes (TOML, KDL, Lua, vimscript) is one where a later statement wins
// or adds, and a structural merge would need a parser per format plus a story
// for conflicts. Appending keeps working when a tool adds a new config key.
func (w *Writer) override(tool, name string) ([]byte, error) {
	if w.Overrides == "" {
		return nil, nil
	}
	b, err := os.ReadFile(filepath.Join(w.Overrides, tool, name))
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("render: reading override for %s/%s: %w", tool, name, err)
	}
	return b, nil
}

// Write puts content at dest, which must be inside Root.
//
// It returns whether the file changed, so an install can report "3 written, 9
// already current" rather than claiming to have rewritten everything.
func (w *Writer) Write(dest string, content []byte) (changed bool, err error) {
	if err := w.inRoot(dest); err != nil {
		return false, err
	}

	existing, err := os.ReadFile(dest)
	switch {
	case errors.Is(err, fs.ErrNotExist):
	case err != nil:
		return false, fmt.Errorf("render: %s: %w", dest, err)
	default:
		if bytes.Equal(existing, content) {
			return false, nil
		}
	}

	if w.DryRun {
		return true, nil
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return false, fmt.Errorf("render: %s: %w", dest, err)
	}
	if err := writeAtomic(dest, content, 0o644); err != nil {
		return false, fmt.Errorf("render: %s: %w", dest, err)
	}
	return true, nil
}

// WriteExec writes an executable file.
func (w *Writer) WriteExec(dest string, content []byte) (bool, error) {
	changed, err := w.Write(dest, content)
	if err != nil || w.DryRun {
		return changed, err
	}
	return changed, os.Chmod(dest, 0o755)
}

// inRoot is the isolation guarantee, checked rather than trusted. A template
// destination is built from configuration, and configuration can contain "..";
// this is the one place that can go wrong, so it is the one place that checks.
func (w *Writer) inRoot(dest string) error {
	if w.Root == "" {
		return fmt.Errorf("render: no root configured")
	}
	abs, err := filepath.Abs(dest)
	if err != nil {
		return fmt.Errorf("render: %s: %w", dest, err)
	}
	root, err := filepath.Abs(w.Root)
	if err != nil {
		return fmt.Errorf("render: %s: %w", w.Root, err)
	}
	rel, err := filepath.Rel(root, abs)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("render: refusing to write outside bothy's tree: %s\n"+
			"      bothy only writes inside %s", dest, root)
	}
	return nil
}

// writeAtomic writes via a temporary file and renames, so an interrupted write
// cannot leave a tool reading a truncated config.
func writeAtomic(dest string, content []byte, mode fs.FileMode) error {
	tmp := dest + ".bothy-tmp"
	if err := os.WriteFile(tmp, content, mode); err != nil {
		return err
	}
	if err := os.Rename(tmp, dest); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}

// funcs is the template function set. It stays small on purpose: a template
// needing more logic than this is a sign the providers should be split instead.
func funcs() template.FuncMap {
	return template.FuncMap{
		"join":  strings.Join,
		"quote": func(s string) string { return fmt.Sprintf("%q", s) },
		"default": func(def, v string) string {
			if v == "" {
				return def
			}
			return v
		},
	}
}
